Debug mode
RobocupUlavalEmbedded/RobotMCU pull request #16
Opened 2017-04-26 23:38 UTC by Gagnon06

Mode de debug ajouté. Il s'agit en fait d'une console accessible par Bluetooth (avec dongle).

2017-04-28 15:31 UTC, PhiBabin requested changes

2017-04-28 15:31 UTC, PhiBabin commented on Robot_stm32f4discovery/Src/robocup/ball_detector.c
> +	uint32_t adcMean = (adcValue1 + adcValue2) / 2;
Pourquoi ne pas utilisé  ball_getSensorsMeanValue() ?

2017-04-28 15:31 UTC, PhiBabin commented on Robot_stm32f4discovery/Src/robocup/com_interfaces/bluetooth.c
> +	if (c == s_endChar) {
A la ligne 63 il faudrait changer le delay pour un yield.

2017-04-28 15:31 UTC, PhiBabin commented on Robot_stm32f4discovery/Src/robocup/console/console.c
> +		if(pCmd[charId] == ' ') {
Il faudrait un check que les commandes ne font pas plus que 25 charatères. Sinon, il va y avoir un overflow

2017-04-28 15:31 UTC, PhiBabin commented on Robot_stm32f4discovery/Src/robocup/console/console.c
> +			parsedCmd[argId][argCharId] = '\0';
Je sortirais la ligne 20 en dehors de la boucle, comme cela si le packet dépasse 255, il va être null terminated

2017-04-28 15:31 UTC, PhiBabin commented on Robot_stm32f4discovery/Src/robocup/console/console.c
> +void console_parseCommand(char pCmd[255], char parsedCmd[10][25]){
La taille de l'array devrait être 256 pour avoir des éléments de 0 à 255. Une taille de 255 donne des éléments de 0 à 254

2017-04-28 15:31 UTC, PhiBabin commented on Robot_stm32f4discovery/Src/robocup/console/console_task.c
> +		if(!strcmp("help", parsedCommand[0])) {
Je ferais une lookup table des commandes du genre:
```C
struct cmdConsole_t{
const char* command; 
void (maCommande)(char*);
};
 cmdConsole_t g_cmds_console [] {
{"help", &print_help},
{"ping", &ping}
}
```

2017-04-28 15:31 UTC, PhiBabin commented on Robot_stm32f4discovery/Src/robocup/console/console_task.c
> +		if(!strcmp("help", parsedCommand[0])) {
Ensuite, j'aurai une boucle qui ittérerait sur les éléments de la lookup table pour trouver quel callback appeler.

2017-04-28 15:31 UTC, PhiBabin commented on Robot_stm32f4discovery/Src/robocup/console/console_task.c
> +		osDelay(1);
use yieldTask instead

2017-04-28 15:31 UTC, PhiBabin commented on Robot_stm32f4discovery/Src/robocup/console/console_task.c
> +			log_metadata();
Je suis pas sûr que cette fonction a sa place dans log. Elle devrait être dans ce fichier.

2017-04-28 15:31 UTC, PhiBabin commented on Robot_stm32f4discovery/Src/robocup/motors/ctrl_task.c
> +			//g_wheels[i].pid = pid_init(PID_P, PID_I, PID_D, 1.0, 0.0);
dead code

2017-04-28 15:31 UTC, PhiBabin commented on Robot_stm32f4discovery/Src/robocup/nrfDriver/nrfDriver.c
> +	if(val == 100)
Un peu trop de valeur magique

2017-04-28 17:04 UTC, sim0504 commented on Robot_stm32f4discovery/Src/robocup/nrfDriver/nrfDriver.c
> +	if(val == 100)
0x03 cest le registre du numero de channel dans le nrf

2017-04-28 17:05 UTC, sim0504 commented on Robot_stm32f4discovery/Src/robocup/nrfDriver/nrfDriver.c
> +	if(val == 100)
oups 0x05, en fait on vérifie que le nrf fonctionne en allant lire l'adresse 0x05 qui contient le channel (100) et en comparant avec le channel qu'on a setté

2017-04-28 17:06 UTC, Gagnon06 commented on Robot_stm32f4discovery/Src/robocup/ball_detector.c
> +	uint32_t adcMean = (adcValue1 + adcValue2) / 2;
Je voulais éviter de faire deux calls de plus sur HAL_ADCEx_... Je ne sais pas ce qui se passe en background.

2017-04-28 17:12 UTC, Gagnon06 commented on Robot_stm32f4discovery/Src/robocup/nrfDriver/nrfDriver.c
> +	if(val == 100)
100 c'est le numéro du channel qui est aussi hard codé plus haut... ;)

2017-04-28 17:23 UTC, PhiBabin commented on Robot_stm32f4discovery/Src/robocup/nrfDriver/nrfDriver.c
> +	if(val == 100)
Je dis qu'il faudrait que les valeurs soit remplacer par une #define/ const int pour que sa soit plus claire quel registre est lue. Il serait aussi utilise que la channel soit une constante.

2017-04-30 23:07 UTC, PhiBabin approved these changes

2017-04-30 23:07 UTC, merged